Decouverte/Models/Ticket.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Decouverte.Models
{
    [Table("t_ticket")]
    public class Ticket{
        [Column("ticket_id")]
        public int TicketId{get;set;}
        [Column("date_create")]
        [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        public DateTime DateCreated{get;set;}
        [Column("date_close")]
        public DateTime? DateClosed{get;set;}
        [Column("object")]
        public string Object{get;set;}
        [Column("title")]
        public string Title{get;set;}
        [Column("client_id")]
        public int ClientId{get;set;}
        [Column("created_by")]
        public int CreatedBy{get;set;}
        [Column("closed_by")]
        public int? ClosedBy{get;set;}

        [ForeignKey("ClientId")]
        public Client Client{get;set;}
        [ForeignKey("CreatedBy")]
        public User UserWhoCreated{get;set;}
        [ForeignKey("ClosedBy")]
        public User UserWhoClosed{get;set;}
    }
}

Decouverte/Controllers/ActionController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Decouverte.Models;

namespace Decouverte.Controllers
{
    public class ActionController : Controller
    {
        [HttpGet]
        public IActionResult Add(int id){
            List<User> myUsers;
            using(var context = new TicketingContext()) {
                myUsers = context.Users.ToList();
            }
            this.ViewData["UserList"] = myUsers;
            this.ViewData["TicketId"] = id;
            return View();
        }
        [HttpPost]
        public IActionResult Add(Models.Action actionObject){
            if(ModelState.IsValid){
                using(var context = new TicketingContext()) {
                    var NewAction = new Models.Action{
                        Description = actionObject.Description,
                        Title = actionObject.Title,
                        UserId = actionObject.UserId,
                        TicketId = actionObject.TicketId,
                        ActionDate = DateTime.Now,
                    };
                    actionObject.ActionDate = DateTime.Now;
                    context.Actions.Add(actionObject);
                    context.SaveChanges();
                }
                return RedirectToAction("Read", "Tickets", new { id = actionObject.TicketId });
            }
            return View();
        }
    }
}

Decouverte/Controllers/TicketsController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Decouverte.Models;
using Microsoft.EntityFrameworkCore;

namespace Decouverte.Controllers
{
    public class TicketsController : Controller
    {
        [HttpGet]
        public IActionResult Index(){
            List<Ticket> mytickets;
            using(var context = new TicketingContext()) {
                mytickets = context.Tickets.Include(t => t.Client).ToList();
            }
            mytickets = mytickets.OrderBy(e => e.DateClosed).ToList();
            List<User> myUsers;
            using(var context = new TicketingContext()) {
                myUsers = context.Users.ToList();
            }
            this.ViewData["UserList"] = myUsers;
            return View(mytickets);
        }
        [HttpGet]
        public IActionResult Read(int id){
            List<Ticket> myTickets;
            List<Models.Action> myActions;
            using(var context = new TicketingContext()) {
                myTickets = context.Tickets.Include(t => t.Client)
                                            .Include(t => t.UserWhoCreated)
                                            .Include(t => t.UserWhoClosed)
                                            .ToList();
                var Ticket = myTickets.Find(e => e.TicketId == id);
                if(Ticket == null)
                    return NotFound($"Le ticket {id} n'existe pas!");

                myActions = context.Actions.Include(t => t.User)
                                            .Where(e => e.TicketId == Ticket.TicketId)
                                            .OrderByDescending(e => e.ActionDate)
                                            .ToList();
                this.ViewData["ActionList"] = myActions;
                return View(Ticket);
            }
        }

        [HttpGet]
        public IActionResult Edit(int id){
            List<Ticket> mytickets;
            using(var context = new TicketingContext()) {
                mytickets = context.Tickets.ToList();
            }
            var Ticket = mytickets.Find(e => e.TicketId == id);
            if(Ticket == null)
                return NotFound($"le ticket {id} n'existe pas!");
            return View(Ticket);
        }

        [HttpPost]
        public IActionResult Edit(int id, Ticket ticket){
            List<Ticket> mytickets;
            using(var context = new TicketingContext()) {
                mytickets = context.Tickets.ToList();
                var old = mytickets.Find(e => e.TicketId == id);
                if(old == null){
                    return NotFound($"le ticket {id} n'existe pas!"); 
                }
                if(ModelState.IsValid){
                    string ActionDescription = "";
                    if (old.Title != ticket.Title)
                        ActionDescription += "Changement du titre - Ancien titre : " + old.Title + "  -  Nouveau titre : " + ticket.Title;
                    if (old.Object != ticket.Object)
                        ActionDescription += "Changement de l'objet - Ancien objet : " + old.Object + "  -  Nouvel objet : " + ticket.Object;
                    old.Title = ticket.Title;
                    old.Object = ticket.Object;
                    var NewAction = new Models.Action{
                        TicketId = old.TicketId,
                        ActionDate = DateTime.Now,
                        UserId = 1,
                        Title = "Modification du Ticket",
                        Description = ActionDescription,
                    };
                    context.Actions.Add(NewAction);
                    context.SaveChanges();
                    return RedirectToAction("Index");
                }
                return View(old);
            }
        }
        [HttpGet]
        public IActionResult Add(){
            List<Client> myCustomers;
            using(var context = new TicketingContext()) {
                myCustomers = context.Clients.ToList();
            }
            this.ViewData["ClientList"] = myCustomers;
            List<User> myUsers;
            using(var context = new TicketingContext()) {
                myUsers = context.Users.ToList();
            }
            this.ViewData["UserList"] = myUsers;
            return View();
        }
        [HttpPost]
        public IActionResult Add(Ticket ticket){
            if(ModelState.IsValid){
                using(var context = new TicketingContext()) {
                    var NewTicket = new Ticket{
                        Object= ticket.Object,
                        Title= ticket.Title,
                        DateCreated = DateTime.Now,
                        ClientId = ticket.ClientId,
                        CreatedBy = ticket.CreatedBy
                    };
                    context.Tickets.Add(NewTicket);
                    context.SaveChanges();
                    var NewAction = new Models.Action{
                        TicketId = NewTicket.TicketId,
                        ActionDate = DateTime.Now,
                        UserId = 1,
                        Title = "Création du Ticket",
                        Description = "Le ticket à été créé",
                    };
                    context.Actions.Add(NewAction);
                    context.SaveChanges();
                }

                return RedirectToAction("Index");
            }
            return View();
        }

        [HttpGet]
        public IActionResult Close(int id, int userId){
            List<Ticket> mytickets;
            using(var context = new TicketingContext()) {
                mytickets = context.Tickets.ToList();
            
                var Ticket = mytickets.Find(e => e.TicketId == id);

                if(Ticket == null)
                    return NotFound($"Le ticket {id} n'existe pas!");

                Ticket.ClosedBy = userId;
                Ticket.DateClosed = DateTime.Now;
                var NewAction = new Models.Action{
                    TicketId = Ticket.TicketId,
                    ActionDate = DateTime.Now,
                    UserId = userId,
                    Title = "Fermeture du Ticket",
                    Description = "Le ticket à été fermé",
                };
                context.Actions.Add(NewAction);
                context.SaveChanges();
                
            }
            return RedirectToAction("Index");
        }
    }
}

Decouverte/Views/Tickets/Add.cshtml
@model Decouverte.Models.Ticket
<h1>Créer un nouveau ticket</h1>
<div id="errorDiv" class="alert alert-danger" role="alert" style="display:none">
</div>
<form asp-action="Add" onsubmit="return validateForm()" method="post">
    <div class="form-group">
        <label asp-for="Title">Titre : </label>
        <input id="titleInput" class="form-control" asp-for="Title" />
    </div>
    <div class="form-group">
        <label asp-for="Object">Objet : </label>
        <textarea id="objectInput" class="form-control" asp-for="Object"></textarea>
    </div>
    <div class="form-group">
        <label asp-for="ClientId">Client : </label>
        <select id="clientSelect" class="form-control" asp-for="ClientId">
            <option value="0">----------</option>
            @foreach(var client in @ViewData["ClientList"] as IList<Client>) {
                <option value="@client.ClientId">@client.Name</option>
            }
        </select>
    </div>
    <div class="form-group">
        <label asp-for="CreatedBy">Utilisateur : </label>
        <select id="userSelect" class="form-control" asp-for="CreatedBy">
            <option value="0">----------</option>
            @foreach(var user in @ViewData["UserList"] as IList<User>) {
                <option value="@user.UserId">@user.LastName @user.FirstName</option>
            }
        </select>
    </div>
    <input class="btn btn-primary" type="submit" value="valider" />
</form>
<script>
    function validateForm() {
        var clientSelect = $('#clientSelect').val();
        var userSelect = $('#userSelect').val();
        var titleInput = $('#titleInput').val();
        var objectInput = $('#objectInput').val();
        var errorMessage = '';
        if (titleInput == '') {
            errorMessage += "Le titre doit être renseigné !<br>"
        }
        if (objectInput == '') {
            errorMessage += "L'objet doit être renseigné !<br>"
        }
        if (clientSelect == 0) {
            errorMessage += "Le client doit être renseigné !<br>"
        }
        if (userSelect == 0) {
            errorMessage += "L'utilisateur doit être renseigné !<br>"
        }
        $('#errorDiv').html(errorMessage);
        $('#errorDiv').show();
        if (errorMessage != '')
            return false;
    }
</script>

Decouverte/Views/Tickets/Edit.cshtml
@model Decouverte.Models.Ticket
<h1>Modification du ticket : @Model.TicketId | @Model.Title</h1>
<form asp-action="Edit" asp-route-id="@Model.TicketId" method="post">
    <div>
        <label asp-for="Title">Nom : </label>
        <input asp-for="Title" />
    </div>
    <div>
        <label asp-for="Object">Object : </label>
        <textarea asp-for="Object"></textarea>
    </div>

    <input type="submit" value="valider" />

    @Html.ValidationMessageFor(m => m.Title)
    <span asp-validation-for="Title"></span>
</form>

Decouverte/Views/Tickets/Index.cshtml
@using System.Collections.Generic;
@*@model List<Decouverte.Controllers.Ticket>*@
@model List<Decouverte.Models.Ticket>
<h1>Liste des tickets</h1>
<a class="btn btn-primary" asp-action="Add" asp-controller="Tickets">Nouveau ticket</a>
<p>Il y a @Model.Count ticket(s).</p>
<table class="table">
    <thead class="thead-dark">
        <tr>
            <th>Titre</th>
            <th>Date ouv</th>
            <th>Date ferm</th>
            <th>Objet</th>
            <th>Client</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach(var ticket in Model) {
            <tr>
                <td>@ticket.Title</td>
                <td>@ticket.DateCreated</td>
                <td>@ticket.DateClosed</td>
                <td>@ticket.Object</td>
                <td>@ticket.Client</td>
                @*<td><a href="/Tickets/Edit/@ticket.Id">Edit</a></td>*@
                <td>
                    <a asp-action="Read" asp-controller="Tickets" asp-route-id="@ticket.TicketId"><i class="fas fa-eye"></i></a>
                    <a asp-action="Edit" asp-controller="Tickets" asp-route-id="@ticket.TicketId"><i class="fas fa-edit"></i></a>
                    <a class="OpenModal" data-id="@ticket.TicketId"><i data-toggle="modal" data-target="#closeModal" class="fas fa-times"></i></a>
                </td>
            </tr>
        }
    </tbody>
</table>
<div class="modal fade" id="closeModal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Fermer le ticket</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <select id="userSelect" class="form-control">
            <option value="0" selected>----------</option>
            @foreach(var user in @ViewData["UserList"] as IList<User>) {
                <option value="@user.UserId">@user.LastName @user.FirstName</option>
            }
        </select>
        <input id="TicketId" type="hidden">
      </div>
      <div class="modal-footer">
        <a id="saveButton" class="btn btn-primary" asp-action="Close" asp-controller="Tickets">Fermer le ticket</a>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Annuler</button>
      </div>
    </div>
  </div>
</div>
<script>
    $(".OpenModal").click(function () {
        var ticketId = $(this).data('id');
        $("#TicketId").val(ticketId);
    });
    $("#saveButton").click(function() {
        var url = "/Tickets/Close/" + $("#TicketId").val() + "?userid=" + $("#userSelect").val();
        $(this).attr("href", url);
    })
</script>

Decouverte/Views/Tickets/Read.cshtml
@model Decouverte.Models.Ticket
<h1>Ticket n°@Model.TicketId</h1>
<div class="container">
    <table class="table table-bordered">
        <thead>
            <th>Label</th>
            <th>Valeur</th>
        </thead>
        <tbody>
            <tr>
                <td>ID Ticket</td>
                <td>@Model.TicketId</td>
            </tr>
            <tr>
                <td>Titre</td>
                <td>@Model.Title</td>
            </tr>
            <tr>
                <td>Objet</td>
                <td>@Model.Object</td>
            </tr>
            <tr>
                <td>Client </td>
                <td>@Model.Client</td>
            </tr>
            <tr>
                <td>Date de création</td>
                <td>@Model.DateCreated</td>
            </tr>
            <tr>
                <td>Date de fermeture </td>
                <td>@Model.DateClosed</td>
            </tr>
            <tr>
                <td>Créé par</td>
                <td>@Model.UserWhoCreated</td>
            </tr>
            <tr>
                <td>Fermé par</td>
                <td>@Model.UserWhoClosed</td>
            </tr>
        </tbody>
    </table>
    <a class="btn btn-primary"  asp-action="Add" asp-controller="Action" asp-route-id="@Model.TicketId">Ajouter action</a>
    @{
        Html.RenderPartial("../Action/Index", @ViewData["ActionList"]);
    }
</div>