Decouverte/Controllers/ClientController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Decouverte.Models;

namespace Decouverte.Controllers
{
    public class ClientController : Controller
    {

        [HttpGet]
        public IActionResult Index()
        {
            List<Client> myClients;
            using (var context = new TicketingContext())
            {
                myClients = context.Clients.ToList();
            }
            Console.WriteLine(myClients);
            return View(myClients);
        }
        [HttpGet]
        public IActionResult Read(int id)
        {
            List<Client> myClients;
            using (var context = new TicketingContext())
            {
                myClients = context.Clients.ToList();
            }
            var Client = myClients.Find(e => e.ClientId == id);
            if (Client == null)
                return NotFound($"Le client {id} n'existe pas!");
            return View(Client);
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            List<Client> myClients;
            using (var context = new TicketingContext())
            {
                myClients = context.Clients.ToList();
            }
            var Client = myClients.Find(e => e.ClientId == id);
            if (Client == null)
                return NotFound($"Le client {id} n'existe pas!");
            return View(Client);
        }

        [HttpPost]
        public IActionResult Edit(int id, Client Client)
        {
            List<Client> myClients;
            using (var context = new TicketingContext())
            {
                myClients = context.Clients.ToList();

                var old = myClients.Find(e => e.ClientId == id);
                if (old == null)
                {
                    return NotFound($"le client {id} n'existe pas!");
                }
                if (ModelState.IsValid)
                {
                    old.Name = Client.Name;
                    old.Address = Client.Address;
                    old.PhoneNumber = Client.PhoneNumber;
                    context.SaveChanges();
                    return RedirectToAction("Index");
                }
                return View(old);
            }
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Add(Client Client)
        {
            if (ModelState.IsValid)
            {
                using (var context = new TicketingContext())
                {
                    var NewClient = new Client
                    {
                        Name = Client.Name,
                        Address = Client.Address,
                        PhoneNumber = Client.PhoneNumber,
                    };
                    context.Clients.Add(NewClient);
                    context.SaveChanges();
                }
                return RedirectToAction("Index");
            }
            return View();
        }

        public IActionResult Delete(int id)
        {
            List<Client> myClients;
            using (var context = new TicketingContext())
            {
                myClients = context.Clients.ToList();

                var Client = myClients.Find(e => e.ClientId == id);

                if (Client == null)
                    return NotFound($"Le client {id} n'existe pas!");

                context.Remove(Client);
                context.SaveChanges();

            }
            return RedirectToAction("Index");
        }
    }
}

Decouverte/Controllers/TicketsController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Decouverte.Models;
using Microsoft.EntityFrameworkCore;

namespace Decouverte.Controllers
{
    public class TicketsController : Controller
    {
        [HttpGet]
        public IActionResult Index(){
            List<Ticket> mytickets;
            using(var context = new TicketingContext()) {
                mytickets = context.Tickets.Include(t => t.Client).ToList();
            }
            mytickets = mytickets.OrderBy(e => e.DateClosed).ToList();
            List<User> myUsers;
            using(var context = new TicketingContext()) {
                myUsers = context.Users.ToList();
            }
            this.ViewData["UserList"] = myUsers;
            return View(mytickets);
        }
        [HttpGet]
        public IActionResult Read(int id){
            List<Ticket> myTickets;
            List<Models.Action> myActions;
            using(var context = new TicketingContext()) {
                myTickets = context.Tickets.Include(t => t.Client)
                                            .Include(t => t.UserWhoCreated)
                                            .Include(t => t.UserWhoClosed)
                                            .ToList();
                var Ticket = myTickets.Find(e => e.TicketId == id);
                if(Ticket == null)
                    return NotFound($"Le ticket {id} n'existe pas!");

                myActions = context.Actions.Include(t => t.User)
                                            .Where(e => e.TicketId == Ticket.TicketId)
                                            .OrderByDescending(e => e.ActionDate)
                                            .ToList();
                this.ViewData["ActionList"] = myActions;
                return View(Ticket);
            }
        }

        [HttpGet]
        public IActionResult Edit(int id){
            List<Ticket> mytickets;
            using(var context = new TicketingContext()) {
                mytickets = context.Tickets.ToList();
            }
            var Ticket = mytickets.Find(e => e.TicketId == id);
            if(Ticket == null)
                return NotFound($"le ticket {id} n'existe pas!");
            return View(Ticket);
        }

        [HttpPost]
        public IActionResult Edit(int id, Ticket ticket){
            List<Ticket> mytickets;
            using(var context = new TicketingContext()) {
                mytickets = context.Tickets.ToList();
                var old = mytickets.Find(e => e.TicketId == id);
                if(old == null){
                    return NotFound($"le ticket {id} n'existe pas!"); 
                }
                if(ModelState.IsValid){
                    string ActionDescription = "";
                    if (old.Title != ticket.Title)
                        ActionDescription += "Changement du titre - Ancien titre : " + old.Title + "  -  Nouveau titre : " + ticket.Title;
                    if (old.Object != ticket.Object)
                        ActionDescription += "Changement de l'objet - Ancien objet : " + old.Object + "  -  Nouvel objet : " + ticket.Object;
                    old.Title = ticket.Title;
                    old.Object = ticket.Object;
                    var NewAction = new Models.Action{
                        TicketId = old.TicketId,
                        ActionDate = DateTime.Now,
                        UserId = 1,
                        Title = "Modification du Ticket",
                        Description = ActionDescription,
                    };
                    context.Actions.Add(NewAction);
                    context.SaveChanges();
                    return RedirectToAction("Index");
                }
                return View(old);
            }
        }
        [HttpGet]
        public IActionResult Add(){
            List<Client> myCustomers;
            using(var context = new TicketingContext()) {
                myCustomers = context.Clients.ToList();
            }
            this.ViewData["ClientList"] = myCustomers;
            List<User> myUsers;
            using(var context = new TicketingContext()) {
                myUsers = context.Users.ToList();
            }
            this.ViewData["UserList"] = myUsers;
            return View();
        }
        [HttpPost]
        public IActionResult Add(Ticket ticket){
            if(ModelState.IsValid){
                using(var context = new TicketingContext()) {
                    var NewTicket = new Ticket{
                        Object= ticket.Object,
                        Title= ticket.Title,
                        DateCreated = DateTime.Now,
                        ClientId = ticket.ClientId,
                        CreatedBy = ticket.CreatedBy
                    };
                    context.Tickets.Add(NewTicket);
                    context.SaveChanges();
                    var NewAction = new Models.Action{
                        TicketId = NewTicket.TicketId,
                        ActionDate = DateTime.Now,
                        UserId = 1,
                        Title = "Création du Ticket",
                        Description = "Le ticket à été créé",
                    };
                    context.Actions.Add(NewAction);
                    context.SaveChanges();
                }

                return RedirectToAction("Index");
            }
            return View();
        }

        [HttpGet]
        public IActionResult Close(int id, int userId){
            List<Ticket> mytickets;
            using(var context = new TicketingContext()) {
                mytickets = context.Tickets.ToList();
            
                var Ticket = mytickets.Find(e => e.TicketId == id);

                if(Ticket == null)
                    return NotFound($"Le ticket {id} n'existe pas!");

                Ticket.ClosedBy = userId;
                Ticket.DateClosed = DateTime.Now;
                var NewAction = new Models.Action{
                    TicketId = Ticket.TicketId,
                    ActionDate = DateTime.Now,
                    UserId = userId,
                    Title = "Fermeture du Ticket",
                    Description = "Le ticket à été fermé",
                };
                context.Actions.Add(NewAction);
                context.SaveChanges();
                
            }
            return RedirectToAction("Index");
        }
    }
}

Decouverte/Controllers/UserController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Decouverte.Models;

namespace Decouverte.Controllers
{
    public class UserController : Controller
    {
        
        [HttpGet]
        public IActionResult Index(){
            List<User> myUsers;
            using(var context = new TicketingContext()) {
                myUsers = context.Users.ToList();
            }
            Console.WriteLine(myUsers);
            return View(myUsers);
        }
         [HttpGet]
        public IActionResult Read(int id){
            List<User> myUsers;
            using(var context = new TicketingContext()) {
                myUsers = context.Users.ToList();
            }
            var User = myUsers.Find(e => e.UserId == id);
            if(User == null)
                return NotFound($"L'utilisateur {id} n'existe pas!");
            return View(User);
        }

        [HttpGet]
        public IActionResult Edit(int id){
            List<User> myUsers;
            using(var context = new TicketingContext()) {
                myUsers = context.Users.ToList();
            }
            var User = myUsers.Find(e => e.UserId == id);
            if(User == null)
                return NotFound($"L'utilisateur {id} n'existe pas!");
            return View(User);
        }

        [HttpPost]

        [HttpPost]
        public IActionResult Edit(int id, User user)
        {
            List<User> myUsers;
            using (var context = new TicketingContext())
            {
                myUsers = context.Users.ToList();

                var old = myUsers.Find(e => e.UserId == id);
                if (old == null)
                {
                    return NotFound($"L'utilisateur {id} n'existe pas!");
                }
                if (ModelState.IsValid)
                {
                    old.Email = user.Email;
                    old.FirstName = user.FirstName;
                    old.LastName = user.LastName;
                    old.PhoneNumber = user.PhoneNumber;
                    context.SaveChanges();
                    return RedirectToAction("Index");
                }
                return View(old);
            }
        }
        [HttpGet]
        public IActionResult Add(){
            return View();
        }
        [HttpPost]
        public IActionResult Add(User user){
            if(ModelState.IsValid){
                using(var context = new TicketingContext()) {
                    var NewUser = new User{
                        FirstName = user.FirstName,
                        LastName = user.LastName,
                        Email = user.Email,
                        PhoneNumber = user.PhoneNumber,
                    };
                    context.Users.Add(NewUser);
                    context.SaveChanges();
                }
                return RedirectToAction("Index");
            }
            return View();
        }
        
        public IActionResult Delete(int id){
            List<User> myUsers;
            using(var context = new TicketingContext()) {
                myUsers = context.Users.ToList();
            
                var user = myUsers.Find(e => e.UserId == id);

                if(user == null)
                    return NotFound($"L'utilisateur {id} n'existe pas!");

                context.Remove(user);
                context.SaveChanges();
                
            }
            return RedirectToAction("Index");
        }
    }
}

Decouverte/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Gestion de Ticket du CESI</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Gestion de Ticket du CESI</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Tickets" asp-action="Index">Tickets</a></li>
                    <li><a asp-area="" asp-controller="User" asp-action="Index">Utilisateurs</a></li>
                    <li><a asp-area="" asp-controller="Client" asp-action="Index">Clients</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - CHAPO CHAPO</p>
        </footer>
    </div>
</body>
</html>